language: node_js
node_js:
  - '10'

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - yarn run test:ci

notifications:
  email: false

branches:
  only: master
